package game;


import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author jacob
 */
public class MainFrame extends javax.swing.JFrame {

	/**
	 * Creates new form MainFrame
	 */

	ImageIcon img = new ImageIcon("images/bts1.resized.png");

	public MainFrame() {
		initComponents();
		setTitle("JK MazeGame");
		setLocationRelativeTo(null);
		setResizable(false);
		jLabel2.setIcon(img);

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		newGameBtn = new javax.swing.JButton();
		HighscoresBtn = new javax.swing.JButton();
		HowToPlayBtn = new javax.swing.JButton();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jPanel1.setBackground(new java.awt.Color(20, 25, 30));
		jPanel1.setBorder(new javax.swing.border.MatteBorder(null));
		jPanel1.setForeground(new java.awt.Color(20, 25, 35));

		newGameBtn.setBackground(new java.awt.Color(20, 25, 35));
		newGameBtn.setFont(new java.awt.Font("Ubuntu", 3, 24)); // NOI18N
		newGameBtn.setForeground(java.awt.Color.pink);
		newGameBtn.setText("New Game");
		newGameBtn.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				newGameBtnActionPerformed(evt);
			}
		});

		HighscoresBtn.setBackground(new java.awt.Color(20, 25, 35));
		HighscoresBtn.setFont(new java.awt.Font("Ubuntu", 3, 24)); // NOI18N
		HighscoresBtn.setForeground(java.awt.Color.pink);
		HighscoresBtn.setText("Highscores");
		HighscoresBtn.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				HighscoresBtnActionPerformed(evt);
			}
		});

		HowToPlayBtn.setBackground(new java.awt.Color(20, 25, 35));
		HowToPlayBtn.setFont(new java.awt.Font("Ubuntu", 3, 24)); // NOI18N
		HowToPlayBtn.setForeground(java.awt.Color.pink);
		HowToPlayBtn.setText("How to play");
		HowToPlayBtn.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				HowToPlayBtnActionPerformed(evt);
			}
		});

		jLabel1.setFont(new java.awt.Font("Ubuntu", 2, 36)); // NOI18N
		jLabel1.setForeground(new java.awt.Color(209, 158, 185));
		jLabel1.setText("JK MazeGame");

		jLabel2.setText("jLabel2");

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addGap(101, 101, 101)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addComponent(HowToPlayBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
								.addComponent(HighscoresBtn, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(newGameBtn, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 518,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(38, 38, 38))
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
						.addContainerGap(326, Short.MAX_VALUE).addComponent(jLabel1,
								javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(314, 314, 314)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
						.addGap(27, 27, 27).addComponent(jLabel1)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										jPanel1Layout.createSequentialGroup()
												.addComponent(newGameBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 89,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGap(44, 44, 44)
												.addComponent(HighscoresBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGap(40, 40, 40).addComponent(HowToPlayBtn,
														javax.swing.GroupLayout.PREFERRED_SIZE, 87,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING,
										javax.swing.GroupLayout.PREFERRED_SIZE, 354,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(105, 105, 105)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void HowToPlayBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_HowToPlayBtnActionPerformed
		dispose();
		new HowToPlay().setVisible(true);
	}// GEN-LAST:event_HowToPlayBtnActionPerformed

	private void newGameBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_newGameBtnActionPerformed
		dispose();
		Game g = new Game();

	}// GEN-LAST:event_newGameBtnActionPerformed

	private void HighscoresBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_HighscoresBtnActionPerformed
		dispose();
		new Highscores().setVisible(true);
	}// GEN-LAST:event_HighscoresBtnActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new MainFrame().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton HighscoresBtn;
	private javax.swing.JButton HowToPlayBtn;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JButton newGameBtn;
	// End of variables declaration//GEN-END:variables

}
